### ISSUE TITLE
исправить колличество отображаемых обвленйи на странице с обылениями где есть левый сайтбар

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#129]
на главнйо странице должно отображаться в ряд 5 обявний, 
на страницах с обылениями где есть левый сайтбар должно быть 4 в ряд, сейчас то 5 то 4 

- 5 - https://market.unifun.com/en/search
- 4 - https://market.unifun.com/category/vehicles/cars
- 5 - https://market.unifun.com/en/search?location=Bissau&r=&c=&sc=
- 5 - https://market.unifun.com/en/category/vehicles

**Comment by solihodjaev1** [comment]
#148
