### ISSUE TITLE
при переходе в объявления (язык PT) -  500 Internal Server Error.

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#134]

**Comment by scorpyar56** [comment]
@hopstee  тут еще вылетает 500-я, даже в английской версии.
![image](https://user-images.githubusercontent.com/51485340/72616148-f470a500-393e-11ea-97d0-e011a24b9067.png)
![image](https://user-images.githubusercontent.com/51485340/72616170-005c6700-393f-11ea-8c1f-79669beecfbb.png)
тоже в DetailsController.php
