### ISSUE TITLE
EN / PT - Page 2 - My Account - https://market.unifun.com/en/account

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#161]
Page 2
EN / PT - My Account - https://market.unifun.com/en/account
обновление, перевод, актуализация slugs - https://market.unifun.com/en/account
пример обновления пути первой ссылки вместо той что выше https://market.unifun.com/en/my-account/personal-data

Актуализировать EN текста 
Добавить PT текста 
Актуализировать slugs - они должны корректно отображаться с “-” между словами
Если в google sheet не указаны какие то нотификации которые есть на странице, указать их в отдельном файле и показать Руслану Крупнову
Если что то непонятно обязательно спросить Руслана Крупнова

Текста выбрать из:  
https://docs.google.com/spreadsheets/d/1Q-2S1hE4pUgRLlj4B9IO9jqTTcfjFHdIxXCI7SbsYRM/edit?usp=sharing 
Вкладка EN / PT - Pages
Строка с заголовком - Page 2 - My Account

**Comment by solihodjaev1** [comment]
#196
