### ISSUE TITLE
EN / PT - Page 4 - Report abuse - https://market.unifun.com/en/posts/753/report

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#163]
Page 4
EN / PT - Report abuse - https://market.unifun.com/en/posts/753/report

на страницу Report abuse юзер попадает со страницы объявления

Актуализировать EN текста 
Добавить PT текста 
Актуализировать нотификации EN / PT
Если в google sheet не указаны какие то нотификации но есть на странице указать их в отдельном файле и показать Руслану Крупнову
 
Протестировать и показать и согласовать с Русланом Крупновым куда и как приходят нотификации - Report abuse от юзеров

Если что то непонятно обязательно спросить Руслана Крупнова

Текста выбрать из:  
https://docs.google.com/spreadsheets/d/1Q-2S1hE4pUgRLlj4B9IO9jqTTcfjFHdIxXCI7SbsYRM/edit?usp=sharing 
Вкладка EN / PT - Pages
Строка с заголовком - Page 4 - Report abuse

**Comment by scorpyar56** [comment]
#199
