### ISSUE TITLE
EN / PT - Page 7 - Contact Us - https://market.unifun.com/en/contact

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#166]
Page 7
EN / PT - Contact Us - https://market.unifun.com/en/contact
пример обновления пути первой ссылки вместо той что выше https://market.unifun.com/en/contact-us

Актуализировать EN текста 
Добавить PT текста 
Актуализировать нотификации EN / PT
Актуализировать slugs - они должны корректно отображаться с “-” между словами

Протестировать, показать и согласовать с Русланом Крупновым куда и как приходят письма - от юзеров
Если в google sheet не указаны какие то нотификации которые есть на странице, указать их в отдельном файле и показать Руслану Крупнову
Если что то непонятно обязательно спросить Руслана Крупнова
 
Текста выбрать из:  
https://docs.google.com/spreadsheets/d/1Q-2S1hE4pUgRLlj4B9IO9jqTTcfjFHdIxXCI7SbsYRM/edit?usp=sharing 
Вкладка EN / PT - Pages
Строка с заголовком - Page 7 - Contact Us

**Comment by scorpyar56** [comment]
#180
