### ISSUE TITLE
Related to issue  EN / PT - Page 2 - My Account - https://market.unifun.com/en/account #161 _________ https://market.unifun.com/en/account вкладка Personal Data  объединить блоки Change Password и Add email в 1 который будет называться Privacy

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#169]
1.
Name *
Phone *
Звездочки должны быть красными 

2. 
Заголовки и строки ввода данных, радиокнопки выравнивать по левому краю - сейчас не ровно.

3. inputs строки ввода данных растянуть на всю длину блоков в моб и десктоп версиях

4. 
объединить блоки Change Password и Add email в 1 который будет называться Privacy

**Comment by solihodjaev1** [comment]
#181
