### ISSUE TITLE
Similar Ads должны отображаться в последовательности - объявления из подкатегории второго уровня - потом категория первого уровня

### ISSUE THREAD

**Issue by nicosstv** [UnifunBPA/mercado#17]
пример еcли пост в категории второго уровня Boats - Watercrafts то вначале Similar Ads 
должны быть из категории Boats - Watercrafts а потом если их нет то остальные из Vehicles

**Comment by Ruslan-Crupnov** [comment]
еслим можно - добавить в логику - привызку к городу - обсудили голосом с Эдиком
