### ISSUE TITLE
счетчики кол-ва допустимых символов в строках ввода данных

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#171]
счетчики кол-ва допустимых символов в строках ввода данных
на странице подачи объявлений
XX characters left

сейчас у нас 
A great title from 10 to 55 characters.

везде где в админке указано  custom fields формат text  и указан Field Length (число символов) 
надо на сайте под  строкой ввода данных
написать XX characters left и делать обратный отсчет символов  
пример https://www.olx.pt/anunciar/?bs=homepage_adding

**Comment by Ruslan-Crupnov** [comment]
![image](https://user-images.githubusercontent.com/59723615/72680617-a7b6d680-3ac4-11ea-86f2-3573e5af560a.png)

**Comment by dragbzh** [comment]
#198
