### ISSUE TITLE
Проблемы с переходами

### ISSUE THREAD

**Issue by TarOlya** [UnifunBPA/mercado#183]
Pt язык:
перекидывает после создания объявления(Pt) на En версию страницы
после отправки письма продавцу перекидывает на английскую версию объявления
при переходе по баннеру перекидывает на английскую версию создания объявления
переход в личный кабинет из Pt приводит в En версию кабинета
по клику по категории в pt версии переходит в en версию категории
кнопка more в similar ads перебрасывает в en версию 
при клике по продавцу в объявлении переходит на англ версию

**Comment by solihodjaev1** [comment]
#292
