### ISSUE TITLE
исправить баг 11 - не понял а где баг ??

### ISSUE THREAD

**Issue by solihodjaev1** [UnifunBPA/mercado#395]
https://docs.google.com/presentation/d/1iDKFz7rkMKmxWYVv_PoF3ZpSu08XGoMX4ilXPncqV_A/edit#slide=id.g7de2c68fff_0_1

не понял а где баг ??

**Comment by nicosstv** [comment]
Не надо изобретать проблемы, которые никогда не возникнут. Если кто-то добавил фотку, удалил фотку, добавил фотку и хочет её удалить - он немножечко идиот. Обновит страницу и удалит.
