### ISSUE TITLE
исправить Sort By в моб версии

### ISSUE THREAD

**Issue by nicosstv** [UnifunBPA/mercado#42]

**Comment by Ruslan-Crupnov** [comment]
Эдик можеш оябснить почему когда с телефона смотрю все ок, а когда инспектом с ПК - осталось криво?

**Comment by Ruslan-Crupnov** [comment]
так же по дефолту с телефона должен быть выделен sort by date когда открываем раскрывающийся список 
и давай наверно выделять не больдом а как в поиске синей плашкой

**Comment by Ruslan-Crupnov** [comment]
насколько я помню версия для пк была ранее норм сделана (дизайн)
сейчас не ок - может испортилась когда над моб работали ?

**Comment by Ruslan-Crupnov** [comment]
![image](https://user-images.githubusercontent.com/59723615/72782033-7278c880-3c2b-11ea-957b-c8b4ebb510cb.png)

**Comment by Ruslan-Crupnov** [comment]
1 надо удленить dropdown menu на один уроверь с поиск все горада 
2 текст сделать по центру (по высоте ) тектосвого поля
