### ISSUE TITLE
баг 24: исправить отправку сообщений в личном кабинете

### ISSUE THREAD

**Issue by solihodjaev1** [UnifunBPA/mercado#427]
https://docs.google.com/presentation/d/1iDKFz7rkMKmxWYVv_PoF3ZpSu08XGoMX4ilXPncqV_A/edit#slide=id.g6ede528200_20_6

слайд 24
выводить правильное имя кому отправлять
убрать отправку незареганным пользователям

**Comment by dragbzh** [comment]
#440
