### ISSUE TITLE
баг 32: в ЛК исправить счетчик ниже My Ads

### ISSUE THREAD

**Issue by solihodjaev1** [UnifunBPA/mercado#431]
https://docs.google.com/presentation/d/1iDKFz7rkMKmxWYVv_PoF3ZpSu08XGoMX4ilXPncqV_A/edit#slide=id.g6eef116749_2_44

чтоб выводит кол тех которые прошли модерацию или в процессе
БЕЗ АРХИВИРОВАННЫХ И ТЕХ КОТОРЫЕ НЕ ПРОШЛИ МОДЕРАЦИЮ

**Comment by dragbzh** [comment]
#435
