### ISSUE TITLE
similar ads исправить отображение

### ISSUE THREAD

**Issue by nicosstv** [UnifunBPA/mercado#48]
https://market.unifun.com/splendid-designed-houses/727

**Comment by nicosstv** [comment]
смотрите скрин в чате

**Comment by Ruslan-Crupnov** [comment]
![image](https://user-images.githubusercontent.com/59723615/72680458-bf8d5b00-3ac2-11ea-9c5a-65e2f26715f1.png)
можно сделать чтобы не обрезалась соследнее обявление ?

**Comment by Ruslan-Crupnov** [comment]
также в моб версии с парва от обявления из Similar Ads сликом большй отступ

**Comment by TarOlya** [comment]
Привет. Я во вторник буду и поэкспериментирую с similar ads

вс, 19 янв. 2020 г., 13:53 Ruslan Crupnov <notifications@github.com>:
