### ISSUE TITLE
Обновить в базе текста PT (категирии + фильтра)

### ISSUE THREAD

**Issue by Ruslan-Crupnov** [UnifunBPA/mercado#730]
https://drive.google.com/drive/folders/1QKQh_8ByDb0b_PO6Q9ZpSvDfEAFygKXy?usp=sharing

файлы 
1. For IT Department - File 1 - Categories & Subcategories - Titles
2. For IT Department - File 2 - Filters (Custom Fields)
3. For IT Department - File 3 - Filters content

**Comment by ScorpyarMK** [comment]
Обновлено
