### ISSUE TITLE
Счетчик объявлений в категории

### ISSUE THREAD

**Issue by TarOlya** [UnifunBPA/mercado#84]
Неверно указывает число объявлений в категории
Категиория(число на главной, число на странице в самой категории)
Vehicles(29, 22)
Electronics(35, 26)
Furniture(28, 26)
For Home...(7, 3)
Property(4, 3)
Fashion(9, 4)
Health...(3, 1)
For kids(11, 8)
Pets(9, 1)
For Farming(3, 1)
For construction(3, 2)
Food Market(5, 1)
Interests...(5, 4)
Business(2, 1)
Services(6, 2)
Jobs(19, 15)
Learning(7, 4)
All other(1, 1)

**Comment by solihodjaev1** [comment]
#151
